# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'sample'

  app.frameworks += ['AVFoundation', 'AudioToolbox', 'CoreMedia', 'MobileCoreServices']

  app.pods do
    pod 'CardIO'
    pod 'SVProgressHUD'
  end

  app.entitlements = { 'get-task-allow' => true }
end
